### ISSUE TITLE
Error in reprex_render_impl()

### ISSUE THREAD

**Issue by shannonrodriguez** [tidyverse/reprex#447] opened 2023-10-18 20:40 UTC
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem
Backtrace:
    ▆
 1. └─reprex::reprex_render(...)
 2.   └─reprex:::reprex_render_impl(input, new_session = TRUE, html_preview = html_preview)
 3.     └─cli::cli_abort(...)
 4.       └─rlang::abort(...)
```r

```

**Comment by hadley** [comment] 2023-11-22 21:03
Sounds like a duplicate of #440

**Closed by hadley** 2023-11-22 21:02 UTC
