### ISSUE TITLE
maybe tidydots doesn't work within a reprex?

### ISSUE THREAD

**Issue by rcorty** [tidyverse/reprex#248] opened 2019-03-31 17:47 UTC
I ran this code in a fresh R session:

```
reprex::reprex(
      x = {
        library(tidyverse)
        
        my_cases <- list(
          Species == 'setosa' ~ 'S',
          TRUE ~ 'other'
        )
        
        as_tibble(iris) %>% 
          mutate(new_label = case_when(!!!my_cases))
      }
    )
```

and got

> Error in enexpr(x) : object 'my_cases' not found

I can't exactly make a reprex because

```
reprex::reprex(
  x = {
    reprex::reprex(
      x = {
        library(tidyverse)
        
        my_cases <- list(
          Species == 'setosa' ~ 'S',
          TRUE ~ 'other'
        )
        
        as_tibble(iris) %>% 
          mutate(new_label = case_when(!!!my_cases))
      }
    )
  }
)
```

gives the same error and does not produce output.  Very meta ;)

The reason I think there might be an issue with `reprex` is that when I run this code in R, I get a different error message:

```
library(tidyverse)

my_cases <- list(
  Species == 'setosa' ~ 'S',
  TRUE ~ 'other'
)

as_tibble(iris) %>% 
  mutate(new_label = case_when(!!!my_cases))
```

> Error in eval_tidy(pair$lhs, env = default_env) : 
>   object 'Species' not found

**Comment by jennybc** [comment] 2019-03-31 19:51
Pretty sure this is a duplicate of #241 and #247. If so, it is fixed in the dev version of reprex. I'm closing but please give me a shout if I've been too hasty.

**Closed by jennybc** 2019-03-31 19:51 UTC

**Comment by rcorty** [comment] 2019-03-31 19:59
Yes looks the same to me. Sorry for duplicate issue.

**Comment by jennybc** [comment] 2019-03-31 20:20
I think the universe is telling me I need to do a reprex release because of this!
