### ISSUE TITLE
Special characters in reprex

### ISSUE THREAD

**Issue by filipwastberg** [tidyverse/reprex#252] opened 2019-04-30 08:35 UTC
I was trying to post an issue for another package about special characters when my `reprex()` failed because of those characters:

```r
reprex::reprex({
  
  library(dplyr)
  
  iris %>% 
    mutate(Species = gsub("a", "å", Species)) %>% 
    group_by(Species) %>% 
    count()
  
})   
```

The output from the reprex is: 
``` r

library(dplyr)

iris %>% 
  mutate(Species = gsub("a", "
#> Error: <text>:5:30: unexpected INCOMPLETE_STRING
#> 4: iris %>% 
#> 5:   mutate(Species = gsub("a", "
#>                                 ^
```

The code runs fine outside of the reprex, any idea why it fails inside?

```

R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252
[4] LC_NUMERIC=C                    LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        ps_1.3.0          packrat_0.5.0     digest_0.6.18     R6_2.4.0          reprex_0.2.1.9000
 [7] evaluate_0.13     rlang_0.3.4       fs_1.2.6          callr_3.1.1       whisker_0.3-2     rmarkdown_1.12.6 
[13] tools_3.5.3       xfun_0.6          compiler_3.5.3    processx_3.3.0    clipr_0.5.0       htmltools_0.3.6  
[19] knitr_1.22      
```

**Comment by jennybc** [comment] 2019-05-15 18:33
I am unable to reproduce this on Windows.

When I execute your exact code, I get a successful reprex.

``` r

library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

iris %>% 
  mutate(Species = gsub("a", "å", Species)) %>% 
  group_by(Species) %>% 
  count()
#> # A tibble: 3 x 2
#> # Groups:   Species [3]
#>   Species        n
#>   <chr>      <int>
#> 1 setoså        50
#> 2 versicolor    50
#> 3 virginicå     50
```

<sup>Created on 2019-05-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/Los_Angeles         
#>  date     2019-05-15                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version    date       lib source        
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)
#>  backports     1.1.4      2019-04-10 [1] CRAN (R 3.6.0)
#>  callr         3.2.0      2019-03-15 [1] CRAN (R 3.6.0)
#>  cli           1.1.0      2019-03-19 [1] CRAN (R 3.6.0)
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)
#>  devtools      2.0.2      2019-04-08 [1] CRAN (R 3.6.0)
#>  digest        0.6.18     2018-10-10 [1] CRAN (R 3.6.0)
#>  dplyr       * 0.8.0.1    2019-02-15 [1] CRAN (R 3.6.0)
#>  evaluate      0.13       2019-02-12 [1] CRAN (R 3.6.0)
#>  fansi         0.4.0      2018-10-05 [1] CRAN (R 3.6.0)
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)
#>  htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.6.0)
#>  knitr         1.22       2019-03-08 [1] CRAN (R 3.6.0)
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.0)
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)
#>  pillar        1.4.0      2019-05-11 [1] CRAN (R 3.6.0)
#>  pkgbuild      1.0.3      2019-03-20 [1] CRAN (R 3.6.0)
#>  pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.6.0)
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.6.0)
#>  processx      3.3.1      2019-05-08 [1] CRAN (R 3.6.0)
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)
#>  purrr         0.3.2      2019-03-15 [1] CRAN (R 3.6.0)
#>  R6            2.4.0      2019-02-14 [1] CRAN (R 3.6.0)
#>  Rcpp          1.0.1      2019-03-17 [1] CRAN (R 3.6.0)
#>  remotes       2.0.4      2019-04-10 [1] CRAN (R 3.6.0)
#>  reprex        0.2.1.9000 2019-05-15 [1] local         
#>  rlang         0.3.4      2019-04-07 [1] CRAN (R 3.6.0)
#>  rmarkdown     1.12       2019-03-14 [1] CRAN (R 3.6.0)
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.0)
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)
#>  testthat      2.1.1      2019-04-23 [1] CRAN (R 3.6.0)
#>  tibble        2.1.1      2019-03-16 [1] CRAN (R 3.6.0)
#>  tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.6.0)
#>  usethis       1.5.0      2019-04-07 [1] CRAN (R 3.6.0)
#>  utf8          1.1.4      2018-05-24 [1] CRAN (R 3.6.0)
#>  vctrs         0.1.0      2018-11-29 [1] CRAN (R 3.6.0)
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.0)
#>  xfun          0.6        2019-04-02 [1] CRAN (R 3.6.0)
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.6.0)
#>  zeallot       0.1.0      2018-01-28 [1] CRAN (R 3.6.0)
#> 
#> [1] C:/Users/jenny/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.0/library
```

</details>

**Comment by jennybc** [comment] 2019-05-18 21:14
I think between:

  * use of **knitr version 1.23**
  * #237 
  * #261 

reprex is handling encoding as well as its dependencies allow (mostly especially the difficulties around encoding on Windows in R itself). I'm closing this. If anyone has a new challenging example, especially one that fails with dev reprex + knitr v1.23, please add it to #262.

**Closed by jennybc** 2019-05-18 21:14 UTC
Labels: encoding �, reprex
