### ISSUE TITLE
embed renv lockfile json in reprex instead of si?

### ISSUE THREAD

**Issue by MilesMcBain** [tidyverse/reprex#365] opened 2021-03-03 01:02 UTC
This is kind of an extension of the `revrex` idea we discussed on Twitter. Would it be cool if a  reprex could carry a lockfile hidden by details tag? 

We could then go further than reversing it, we could reverse and attempt to automatically reproduce it from the github issue. 

If you can reproduce from the lockfile environment, but not from an up to date one, it suggests nothing to do. Then imagine putting this in the hands of GitHub bots...

**Comment by jennybc** [comment] 2021-03-03 16:32
Duplicate of #313. See that thread for the solution you seek.

**Closed by jennybc** 2021-03-03 16:32 UTC
