### ISSUE TITLE
Error when using reprex with purrr and paste0(): Error in paste0("is", .x) : object '.x' not found

### ISSUE THREAD

**Issue by andresrcs** [tidyverse/reprex#247] opened 2019-03-28 21:14 UTC
I was trying to make a reprex for answering a questions on community.rstudio.com but I get this error message `Error in paste0("is", .x) : object '.x' not found`, altought that code runs ok on the R console

```r
reprex::reprex({
    library(dplyr)
    library(purrr)
    df <- data.frame( AA = runif(10), AB = runif(10), AC = runif(10),
                      BA = runif(10), BB = runif(10), BC = runif(10),
                      top1 = c("AA","AB","AA","AA","AA","AA","AA","AA","AA","AC"),
                      top2 = c("BA","BC","AC","BB","AB","AB","BA","BB","AC","AB"),
                      top3 = c("BB","AA","BA","BA","BC","BA","BB","BA","BA","AB"),
                      stringsAsFactors = FALSE
    )
    
    df %>% 
        cbind(map_dfc(df %>%
                          select(starts_with("top")) %>%
                          unlist(use.names = FALSE) %>%
                          unique(), 
                      ~df %>%
                          select(starts_with("top")) %>% 
                          transmute(!!paste0("is", .x) := if_else(rowSums(df == .x) > 0, TRUE, FALSE))
        ))
})
```

**Comment by cderv** [comment] 2019-03-29 10:27
Let's note reprex is working fine when code is read from the clipboard. 
The error comes from `enexpr()` that is call on this expression. Here is a more minimal reprex to reproduce `reprex()` behavior
``` r
reprex_min <- function(x = NULL) {x_expr <- rlang::enexpr(x)}
reprex_min({
  library(magrittr)
  purrr::map(c("a", "b"), ~ iris %>% dplyr::transmute(!!paste0("is", .x) := TRUE))
})
#> Error in paste0("is", .x): objet '.x' introuvable
```

<sup>Created on 2019-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

This is not related to `purrr` as this gives no error
``` r
reprex_min <- function(x = NULL) {x_expr <- rlang::enexpr(x)}
reprex_min({
  library(magrittr)
  purrr::map(c("a", "b"), ~ paste0("is", .x))
})
```

So this is more complex with a mix between all the tidyeval stuff I think... 🤔 

Hope it helps.

**Comment by jennybc** [comment] 2019-03-29 14:54
It works for me. If I execute @andresrcs's exact call I get this:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(purrr)
df <- data.frame( AA = runif(10), AB = runif(10), AC = runif(10),
                  BA = runif(10), BB = runif(10), BC = runif(10),
                  top1 = c("AA","AB","AA","AA","AA","AA","AA","AA","AA","AC"),
                  top2 = c("BA","BC","AC","BB","AB","AB","BA","BB","AC","AB"),
                  top3 = c("BB","AA","BA","BA","BC","BA","BB","BA","BA","AB"),
                  stringsAsFactors = FALSE
)

df %>% 
  cbind(map_dfc(df %>%
                  select(starts_with("top")) %>%
                  unlist(use.names = FALSE) %>%
                  unique(), 
                ~df %>%
                  select(starts_with("top")) %>% 
                  transmute(!!paste0("is", .x) := if_else(rowSums(df == .x) > 0, TRUE, FALSE))
  ))
#>             AA         AB         AC          BA         BB           BC
#> 1  0.633995863 0.71875646 0.06519546 0.124583581 0.95536834 0.3217497650
#> 2  0.477842949 0.24840446 0.85715852 0.052297732 0.23196340 0.1830526819
#> 3  0.536564332 0.24353483 0.30382019 0.550887641 0.29349775 0.8653470899
#> 4  0.936227058 0.66416055 0.98218344 0.007870605 0.73999147 0.3286833342
#> 5  0.047026495 0.62130129 0.01530017 0.636289219 0.02145333 0.2409162337
#> 6  0.315151880 0.11197979 0.56008050 0.005518229 0.73751989 0.7691025166
#> 7  0.003113589 0.89598180 0.88812421 0.797637855 0.43601981 0.0550828744
#> 8  0.626487037 0.49663580 0.70178101 0.305517291 0.01025179 0.0006872648
#> 9  0.465103841 0.28932936 0.90118270 0.286490734 0.38662957 0.3374363643
#> 10 0.798718146 0.05636458 0.94682517 0.673579783 0.58591127 0.4397956154
#>    top1 top2 top3  isAA  isAB  isAC  isBA  isBC  isBB
#> 1    AA   BA   BB  TRUE FALSE FALSE  TRUE FALSE  TRUE
#> 2    AB   BC   AA  TRUE  TRUE FALSE FALSE  TRUE FALSE
#> 3    AA   AC   BA  TRUE FALSE  TRUE  TRUE FALSE FALSE
#> 4    AA   BB   BA  TRUE FALSE FALSE  TRUE FALSE  TRUE
#> 5    AA   AB   BC  TRUE  TRUE FALSE FALSE  TRUE FALSE
#> 6    AA   AB   BA  TRUE  TRUE FALSE  TRUE FALSE FALSE
#> 7    AA   BA   BB  TRUE FALSE FALSE  TRUE FALSE  TRUE
#> 8    AA   BB   BA  TRUE FALSE FALSE  TRUE FALSE  TRUE
#> 9    AA   AC   BA  TRUE FALSE  TRUE  TRUE FALSE FALSE
#> 10   AC   AB   AB FALSE  TRUE  TRUE FALSE FALSE FALSE
```

<sup>Created on 2019-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

What version of reprex do you have? I believe this is what I fixed in https://github.com/tidyverse/reprex/commit/5466dae5a2f07f47e996e33f7c029ccae24bf394. So you'd need the dev version of GitHub to get that.

**Closed by jennybc** 2019-03-29 14:54 UTC

**Comment by jennybc** [comment] 2019-03-29 14:55
Basically this is a duplicate of #241
